### ISSUE TITLE
JDash 4.1 Checklist (GD 2.2 support)

### ISSUE THREAD

**Issue by Alex1304** [Alex1304/jdash#42]
## `jdash-common`
- [ ] Update `GDLevel` to support Platformer mode
- [ ] Revamp difficulty icons to be locally generated so as to include Legendary and Mythic ratings
- [ ] Update  ̀GDUserProfile` to add moons and detailed demon count
- [ ] Add level lists

## `jdash-client`
- [ ] Add new search modes: Sent, Daily/Weekly Safe, level lists
- [ ] Improve leaderboard browsing

## `jdash-events`
- [ ] Add events for GD Leaderboard Moderator promote/demote
- [ ] Emit Edit events when Legendary/Mythic state changes

## `jdash-graphics`
- [ ] Add 2.2 icons and colors
- [ ] Add Swing and Jetpack to icon set generator
